# Generated by Django 5.2.5 on 2025-08-23 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название источника')),
                ('tag', models.CharField(choices=[('Book', 'Книга'), ('Movie', 'Фильм'), ('Series', 'Сериал'), ('Game', 'Игра'), ('Scientific article', 'Научная статья'), ('Other', 'Другое')], max_length=20, verbose_name='Тег')),
            ],
            options={
                'unique_together': {('title', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(verbose_name='Текст цитаты')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Вес')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Цитаты', to='quotes.source', verbose_name='Источник цитаты.')),
            ],
            options={
                'unique_together': {('source', 'quote_text')},
            },
        ),
    ]
