# Generated by Django 5.2.5 on 2025-08-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Quote',
        ),
    ]
