# Generated by Django 5.2.5 on 2025-08-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_qoute_quote'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Цитаты', to='sources.source', verbose_name='Источник цитаты.'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
