# Generated by Django 5.2.5 on 2025-08-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название источника')),
                ('tag', models.CharField(choices=[('Book', 'Книга'), ('Movie', 'Фильм'), ('Series', 'Сериал'), ('Game', 'Игра'), ('Scientific article', 'Научная статья'), ('Other', 'Другое')], max_length=20, verbose_name='Тег')),
            ],
            options={
                'unique_together': {('title', 'tag')},
            },
        ),
    ]
